version: "3.8"

services:
  telegram-bot:
    build: .
    container_name: weather_storm_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data  # если бот что-то сохраняет туда
